### ISSUE TITLE
Game stops responding to the keys once the script is loaded.

### ISSUE THREAD

**Issue by Dark-Angel0813** [aditya-jagdev/blur-autoHotKey-Script#1]
When I tried to load the script the game stopped responding to anything. Once I closed autohotkey it started working fine.
I tried toggling on/off but the game doesn't respond as long as autohotkey is running. Any ideas for troubleshooting?

**Comment by simian-kernel** [comment]
Let me have a look. Request you to please share the game version you are using or where you got it from, and the operating system that you are using.

EDIT: Also, the AutoHotKey version please.

**Comment by Dark-Angel0813** [comment]
Game version: Unknown
Autokey version : 1.1.33.10 (latest on their website)

OS Details:
Edition	Windows 10 Pro
Version	21H1
OS build	19043.1466
Experience	Windows Feature Experience Pack 120.2212.3920.0

Game download link:  https://drive.google.com/open?id=1_R4u8PB9HCiTdVXOtRcdJyUcvk3kGnU1&fbclid=IwAR2HTa8KXtnEAPTQRE15fujNsQ_8lF6QQFiHzkSeKPGpZ4asL9zN-2kptyw

Actually I am not sure what is the version of the game but I can provide the link from where I downloaded it.
We have a blur community where we are trying to resurrect this game.

**Comment by simian-kernel** [comment]
Thank you for the detailed response.
An update has been pushed. I'd request you to please test it and provide feedback.

**Comment by simian-kernel** [comment]
Received confirmation offline. Closing the issue.
