### ISSUE TITLE
Blur AutoHotkey

### ISSUE THREAD

**Issue by Artas97** [aditya-jagdev/blur-autoHotKey-Script#2]
Is there a way I can use your script but modify it like "keyboard 2" layout on the actual game but instead of "look behind" being PgDn I want it to be "b" or something...

**Comment by simian-kernel** [comment]
Sure, I'd recommend the following:

- Note down the `Keyboard 2` layout.
- Change the `Look Behind` key bind in your notes.
- Modify the `*.ahk` file that you downloaded, starting at the line [here](https://github.com/aditya-jagdev/blur-autoHotKey-Script/blob/8129a730f8f982ff30763f455861854e7d3394ab/Main/Blur_Custom_Controls.ahk#L18) to match the controls you want.
